### ISSUE TITLE
Error using topquadrant shacl

### ISSUE THREAD

**Issue by lazlop** [gtfierro/shacl-issues#2]
Hi Gabe, I'm getting an error running test cases using topquadrant shacl:

```
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.4.2&fromImage=ghcr.io%2Ftopquadrant%2Fshacl: Internal Server Error ("Head "https://ghcr.io/v2/topquadrant/shacl/manifests/1.4.2": unauthorized")
```

Did you encounter this error?

**Comment by gtfierro** [comment]
I don't think I've run into this, but it might be an issue with docker configuration that we need to either document in the README or fix in a script. Have you run the `build-topbraid-shacl.sh` script?

**Comment by lazlop** [comment]
That worked! I thought I had done it but it appears not. It may be a good idea to add to the readme.

**Comment by gtfierro** [comment]
Just added a note to the README!
